### ISSUE TITLE
'Export failed' message on exporting in Flatpak

### ISSUE THREAD

**Issue by func0der** [Daniele-rolli/Beaver-Notes#167]
**Bug Description**
I get 'Export failed' on exporting, but yet it seems to be going fine. There ARE exported files in the directory and I can import them.
I guess it is because of JS error happening.

**To Reproduce**
1. Choose any path to export to in the settings
2. "Export"

**Expected Behavior**
Export without failure

**Screenshots**
![image](https://github.com/Daniele-rolli/Beaver-Notes/assets/529819/081fa5ea-98b0-4e31-a69d-4119ca71e5e0)

**Desktop (please complete the following information):**
- Device Specification: 
- OS: Fedora 39
- Application Version: 3.1.0

**Additional Context**
Log from the developer console
```
AppSidebar.vue:219 Error: ENOENT: no such file or directory, lstat '/home/user/.var/app/com.beavernotes.beavernotes/config/Beaver-notes/file-assets'
G @ AppSidebar.vue:219
await in G (async)
XE.Ee.onClick.e.<computed>.e.<computed> @ AppSidebar.vue:46
Hs @ runtime-core.esm-bundler.js:193
$r @ runtime-core.esm-bundler.js:201
n @ runtime-dom.esm-bundler.js:671
Show 3 more frames
Show less

```

**Comment by Daniele-rolli** [comment]
Thanks for the feedback! At first glance, it seems like the export is looking for the file-assets folder. I'll work on fixing it ASAP; it should be an easy fix and will be part of release 3.1.1, which should be ready by tomorrow since we've found out about a couple of bugs that jeopardize the user experience as a whole. Thanks again for reporting this issue.

**Comment by func0der** [comment]
Is it correct that export looks only like this? 
![image](https://github.com/Daniele-rolli/Beaver-Notes/assets/529819/bbba51cd-da2e-48b6-8c2b-8a0545c0b6d5)

I kinda expected markdown files (and a folder structure) :thinking:

**Comment by Daniele-rolli** [comment]
Beaver actually puts images in a folder structure and files in their own folders. The notes are stored in a .json since Tiptap supports either storing in .json or .html format. This allows us to create custom extensions and complex features that wouldn't be available in a markdown file. For what it's worth, we are working on a way to export and import data as markdown so that users can migrate to and from Beaver. That said, the export folder looks right.

**Comment by Daniele-rolli** [comment]
This issue has been fixed in release 3.1.1. Thanks again for reporting it to us.

**Comment by polluxau** [comment]
this is still happening for both export and import 

![image](https://github.com/Beaver-Notes/Beaver-Notes/assets/81181814/a56c70cb-2a4c-4b36-844e-445d29ce26bf)

![image](https://github.com/Beaver-Notes/Beaver-Notes/assets/81181814/bb99c02d-f3a1-44e5-850e-6085d0c3067a)
